server:
  port: 8080
  error:
    include-message: always
spring:
  profiles:
    include: dev
  application:
    name: _
  datasource:
    url: _
    username: _
    password: _
    driver-class-name: _
  jpa:
    hibernate:
      ddl-auto: _
    show-sql: true
    properties:
      hibernate:
        dialect: _
    database: mysql
springdoc:
  swagger-ui:
    path: /swagger-ui.html