server:
  port: 8080
  error:
    include-message: always
  tomcat:
    # set it to something (like 50MB) to not let tomcat cancel the requests
    max-swallow-size: _
spring:
  profiles:
    include: dev
  application:
    name: _
  datasource:
    url: _
    username: _
    password: _
    driver-class-name: _
  jpa:
    hibernate:
      ddl-auto: _
    show-sql: true
    properties:
      hibernate:
        dialect: _
    database: mysql
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  servlet:
    multipart:
      # set these to something for the s3 configuration
      max-file-size: _
      max-request-size: _
springdoc:
  swagger-ui:
    path: /swagger-ui.html
aws:
  bucketName: _