server:
  port: 8080
  error:
    include-message: always
spring:
  profiles:
    include: dev
  application:
    name: placeholder
  datasource:
    url: placeholder
    username: placeholder
    password: placeholder
    driver-class-name: placeholder
  jpa:
    hibernate:
      ddl-auto: placeholder
    show-sql: true
    properties:
      hibernate:
        dialect: placeholder
    database: mysql
  security:
    user:
      name: placeholder
      password: placeholder
springdoc:
  swagger-ui:
    path: /swagger-ui.html
jwt:
  secret-key: 1234abcd1234abcd1234abcd1234abcd1234abcd1234abcd1234abcd1234abcd
