server:
  port: 8082
  error:
    include-message: always
spring:
  profiles:
    include: dev
  application:
    name: _
  datasource:
    url: _
    username: _
    password: _
    driver-class-name: _
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: _
    database: mysql
  security:
    user:
      name: _
      password: _
springdoc:
  swagger-ui:
    path: /swagger-ui.html
jwt:
  secret-key: 1234abcd1234abcd1234abcd1234abcd1234abcd1234abcd1234abcd1234abcd
