server:
  port: 8083
  error:
    include-message: always
    include-stacktrace: never
  tomcat:
    # set this to something (for ex 10MB) to not let tomcat cancel the requests
    max-swallow-size: 10MB
spring:
  profiles:
    include: dev
  application:
    name: app_name
  datasource:
    # db settings
    url: jdbc:mysql://localhost:3306/name_of_db
    username: user_name
    password: user_pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    database: mysql
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  servlet:
    multipart:
      # set these to something for the s3 configuration
      max-file-size: 2MB
      max-request-size: 10MB
      resolve-lazily: true
logging:
  level:
    org:
      springframework:
        web: INFO
springdoc:
  swagger-ui:
    path: /swagger-ui.html
aws:
  bucketName: name_of_aws_bucket
app:
  countries-and-regions-filename: countries_and_regions.json