spring:
  profiles:
    include: dev
  security:
    user:
      name: user
      password: password

# # fill these in the application-dev.yml
# spring:
#   datasource:
#     url:
#     username:
#     password:
#     driver-class-name:
#   jpa:
#     hibernate:
#       ddl-auto:
#     show-sql:
#     properties:
#       hibernate:
#         dialect:
#     database:

# jwtSecret: