server:
  port: 8080
  error:
    include-message: always
spring:
  profiles:
    include: dev
  security:
    user:
      name: user
      password: password
springdoc:
  swagger-ui:
    path: /swagger-ui.html

# # fill these in the application-dev.yml
# spring:
#   application:
#     name: ___
#   datasource:
#     url: ___
#     username: ___
#     password: ___
#     driver-class-name: ___
#   jpa:
#     hibernate:
#       ddl-auto: ___
#     show-sql: ___
#     properties:
#       hibernate:
#         dialect: ___
#     database: ___
# jwt:
#   secret-key: ___
