server:
  port: 8080
  error:
    include-message: always
spring:
  profiles:
    include: dev
  application:
    name: iungoreal
  datasource:
    url: jdbc:mysql://localhost:3306/iungorealdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: username_here
    password: password_here
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    database: mysql
  security:
    user:
      name: user
      password: password
springdoc:
  swagger-ui:
    path: /swagger-ui.html
jwt:
  secret-key: 1234abcd1234abcd1234abcd1234abcd1234abcd1234abcd1234abcd1234abcd
